apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gcloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gcloud
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 100