apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcloud
  namespace: default
spec:
  selector:
    matchLabels:
      app: gcloud
  replicas: 1
  template:
    metadata:
      name: gcloud
      labels:
        app: gcloud
    spec:
      containers:
      - name: gcloud
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                 name: postgres-secrets
                 key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: postgres-secrets
                 key: password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: jmacgyve/tpos2goldyrev:0.1